name: "${project.name}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
version: "${project.version}"
api-version: "1.14"
author: Jikoo
description: Distribute rules and guides in item form to players.

permissions:
  rulebooks.admin:
    description: Allows access to all commands.
    children:
      rulebooks.edit: true
      rulebooks.reload: true
      rulebooks.give: true
      rulebooks.get: true
  rulebooks.reload:
    description: Permission to reload rules from disk.
    default: op
  rulebooks.edit:
    description: Permission to alter rules.
    default: op
  rulebooks.give:
    description: Permission to give another player rules.
    default: op
  rulebooks.get:
    description: Permission to get rules.
    default: true
